import React from 'react';

const PrivacyText = () => {
  return (
    <p><i>7.12.2020</i><br/><br/>

      Bloben developer built the Bloben Calendar and Bloben Notes apps (as Bloben) as a Free app. This SERVICE is provided by Bloben developer at no cost and is intended for use as is.
      <br/> <br/>
      This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.
      <br/> <br/>
      If you choose to use our Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.
      <br/> <br/>
      The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Bloben unless otherwise defined in this Privacy Policy.
      <br/><br/><b>Information Collection and Use</b>
      <br/>
      The app does not use third party services that may collect information used to identify you. We use only simple custom analytics which cannot be used to identify you.
        We get only four information. First is referrer - url address where you clicked on the link (for example social site) and timezone location for general geolocation. Your IP address is not used for geolocation and it is also not stored.
        We also store boolean flag if you your screen has width bellow or above breakpoint value without exact number and if your are visiting site as registered user.
        All information are stored anonymously and no user can be identified with them.
        This info is shared directly to Bloben's servers, no third party analytics is used. We do not store any information about what you do while visiting Bloben web and Bloben apps.
      <br/><br/><b>Log Data</b>
      <br/>
      We store information when you opened your account, last time you logged in, when you updated account and your basic settings. We store your email address if you set it for receiving updates and notifications.
      <br/><br/><b>Cookies</b>
      <br/>
      Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. For service no third-party cookies are used. Only cookies, which are used are to verify your identity when you log in to your account and connect to server.
      <br/><br/><b>Service Providers</b>
      <br/>
      We use browser's native Web Push service to send push notifications. You will be asked for permission before. No content except dates are or category is displayed in notification. No other third-party companies and individuals are used.
      <br/><br/><b>Security</b>
      <br/>
      No method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.
      <br/><br/><b>Links to Other Sites</b>
      <br/>
      This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
      <br/><br/><b>Children’s Privacy</b>
      <br/>
      These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13.
      <br/><br/><b>Changes to This Privacy Policy</b>
      <br/>
      We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.
      <br/><br/><b>Contact Us</b>
      <br/>
      If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact us at hello@bloben.com.
      <br/>
      This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator.</p>
  )
}

export default PrivacyText;


